kind: Service
apiVersion: v1
metadata:
  name: mediawiki-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: mediawiki-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80