---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-frontend-service
spec:
  selector:
    app: mediawiki-frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer